### ISSUE TITLE
Crashing the C4Amp

### ISSUE THREAD

**Issue by DeviousAl** [kmakar89/Home-Assistant---Control4#2]
I have a weird one where it seems to crash the amp - I think it's too many socket calls in a time period, I'm not sure. Has anyone else seen this?

C4-8AMP1-B - 03.24.45

Trigger is sending the "off" to the varying zones / rooms I have setup.

Maybe a rate limit needed?

Thanks for creating this @kmakar89 - big help in moving away from C4 like you!

**Comment by kmakar89** [comment]
> I have a weird one where it seems to crash the amp - I think it's too many socket calls in a time period, I'm not sure. Has anyone else seen this?
> 
> C4-8AMP1-B - 03.24.45
> 
> Trigger is sending the "off" to the varying zones / rooms I have setup.
> 
> Maybe a rate limit needed?
> 
> Thanks for creating this @kmakar89 - big help in moving away from C4 like you!

New one to me. I'd check the code to make sure it's setup right. I'm still using this same code and it works flawlessly.

Are you sending volume commands, or switching input or zones?

**Comment by DeviousAl** [comment]
I was calling the switch toggle from a lovelace card:

entities:
  - entity: switch.kitchen_switch
    name: On/Off

So it shows up as a toggle on the dashboard to then turn on/off the input

**Comment by DeviousAl** [comment]
> I was calling the switch toggle from a lovelace card:
> 
> entities:
> 
> * entity: switch.kitchen_switch
>   name: On/Off
> 
> So it shows up as a toggle on the dashboard to then turn on/off the input

I was calling the switch toggle from a lovelace card:

entities:

entity: switch.kitchen_switch
name: On/Off
So it shows up as a toggle on the dashboard to then turn on/off the input

**Comment by DeviousAl** [comment]
> > I have a weird one where it seems to crash the amp - I think it's too many socket calls in a time period, I'm not sure. Has anyone else seen this?
> > C4-8AMP1-B - 03.24.45
> > Trigger is sending the "off" to the varying zones / rooms I have setup.
> > Maybe a rate limit needed?
> > Thanks for creating this @kmakar89 - big help in moving away from C4 like you!
> 
> New one to me. I'd check the code to make sure it's setup right. I'm still using this same code and it works flawlessly.
> 
> Are you sending volume commands, or switching input or zones?

I was calling the switch toggle from a lovelace card:

entities:
  - entity: switch.kitchen_switch
    name: On/Off

So it shows up as a toggle on the dashboard to then turn on/off the input

![Capture](https://user-images.githubusercontent.com/94678223/143077233-2fe7ef7c-b9f7-4330-a814-ac7d289b996c.PNG)

**Comment by kmakar89** [comment]
Post the code you modified (the python) calling your zones and power.

**Comment by DeviousAl** [comment]
> Post the code you modified (the python) calling your zones and power.

            import logging
            import socket
            import random
            from time import sleep
             
            _LOGGER = logging.getLogger(__name__)
             
            DOMAIN = 'c4_services'
             
            def send_udp_command(command, host, port):
                COUNTER = "0s2a" + str(random.randint(10, 99))
                COMMAND = COUNTER + " " + command + " \r\n"
                _LOGGER.warn("Sending command: %s", COMMAND)
                HOST = host
                PORT = port
                
                sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                sock.sendto( bytes(COMMAND, "utf-8"), (HOST, PORT))
                received = str(sock.recv(1024), "utf-8")
                _LOGGER.warn("Command sent. Response: %s", str(received))
                
            def setup(hass, config):
            
                # Kitchen
                
                def handle_kitchen_amp_off_select(call):
                    #_LOGGER.warn("Powering AMP Off...")
                    send_udp_command("c4.amp.out 01 00", "192.168.0.35", 8750)
                    #_LOGGER.warn("AMP Powered Off...")
             
                def handle_kitchen_amp_on_select(call):
                    #_LOGGER.warn("Powering AMP On...")
                    amp_input = hass.states.get("input_select.kitchen_amp_input").state[:1]
                    send_udp_command("c4.amp.chvol 01 a9", "192.168.0.35", 8750)
                    send_udp_command("c4.amp.out 01 0" + amp_input, "192.168.0.35", 8750)
                    #_LOGGER.warn("AMP Powered On...")
            
                def handle_kitchen_amp_volume_select(call):
                    #_LOGGER.warn("Changing amp volume...")
                    volume_select = hass.states.get("input_number.kitchen_amp_volume").state
                    volume_select = int(float(volume_select) * 100) + 160
                    volume_select = hex(volume_select)[2:]
                    send_udp_command("c4.amp.chvol 01 " + volume_select, "192.168.0.35", 8750)
                    #_LOGGER.warn("Volume set...")
                    
                def handle_kitchen_amp_input_select(call):
                    #_LOGGER.warn("Changing amp input...")
                    amp_input = hass.states.get("input_select.kitchen_amp_input").state[:1]
                    amp_input = hex(int(amp_input))[2:]
                    send_udp_command("c4.amp.out 01 0" + amp_input, "192.168.0.35", 8750)
                    #_LOGGER.warn("Amp input changed...")

**Comment by DeviousAl** [comment]
Config:

        # Service
        c4_services:
        
        input_select:
          kitchen_c4_input:
            name: Audio Input
            options:
              - House Chromecast
          kitchen_amp_input:
            name: Zone Input
            options:
              - 1
        input_number:
          kitchen_amp_volume:
            name: Volume
            min: 0
            max: 1
            step: .01
            initial: .04
        input_boolean:
          switch_state_1:
            name: Kitchen Switch
        switch:
          - platform: template
            switches:
              kitchen_switch:
                friendly_name: Kitchen
                unique_id: kitchen_c4_switch_uid
                value_template: "{{ is_state('input_boolean.switch_state_1', 'on') }}"
                turn_on:
                  - service: c4_services.handle_kitchen_amp_on_select
                  - service: input_boolean.turn_on
                    data:
                      entity_id: input_boolean.switch_state_1
                turn_off:
                  - service: c4_services.handle_kitchen_amp_off_select
                  - service: input_boolean.turn_off
                    data:
                      entity_id: input_boolean.switch_state_1


Lastly - I then have my rooms as the Zones - Lounge / Office / Kitchen / Garden. Right now I have a single input, a Chromecast, so the ifelse defaults to that 1st input - then I was using the on/off as a way of "grouping" effectively.

**Comment by kmakar89** [comment]
Post the automation sequence you modified.

**Comment by DeviousAl** [comment]
> 

          - id: Kitchen Amp Volume
            alias: Kitchen Amp Volume
            trigger:
              platform: state
              entity_id: input_number.kitchen_amp_volume
            action:
            - service: c4_services.handle_kitchen_amp_volume_select
          - id: Kitchen AMP Input
            alias: Kitchen Amp Input
            trigger:
              platform: state
              entity_id: input_select.kitchen_amp_input
            action:
              service: c4_services.handle_kitchen_amp_input_select
          - id: Kitchen AMP On
            alias: Kitchen AMP On
            trigger:
              platform: state
              entity_id: input_select.kitchen_amp_on
            action:
              service: c4_services.handle_kitchen_amp_on_select
          - id: Kitchen AMP Off
            alias: Kitchen Amp Off
            trigger:
              platform: state
              entity_id: input_select.kitchen_amp_off
            action:
              service: c4_services.handle_kitchen_amp_off_select
          - id: Kitchen Amp Input Override
            alias: Kitchen Amp Input Override
            trigger:
            - platform: state
              entity_id: input_select.kitchen_c4_input
            action:
            - service: input_select.select_option
              entity_id: input_select.kitchen_amp_input
              data_template:
                option: '{% if is_state(''input_select.kitchen_c4_input'', ''House Chromecast'')
                  %}1 {% elif is_state(''input_select.kitchen_c4_input'', ''House Sonos'') %}2
                  {% elif is_state(''input_select.kitchen_c4_input'', ''Control4 Input'') %}3
                  {%elif is_state(''input_select.kitchen_c4_input'', ''Blank2'') %}4 {% else
                  %}1 {%- endif %}'
            initial_state: true

I will admit that for some reason the formatting on the input_select.kitchen_c4_input keeps messing about for things like the carriage returns on the lines and removes the >- etc so I keep editing it back to:

        option: >-
            {% if is_state('input_select.kitchen_c4_input', 'House Chromecast') %}1
            {% elif is_state('input_select.kitchen_c4_input', 'House Sonos') %}2
            {% elif is_state('input_select.kitchen_c4_input', 'Control4 Input') %}3
            {% elif is_state('input_select.kitchen_c4_input', 'Blank2') %}4
            {% else %}1
            {%- endif %}

I can probably do away with it for now, as only keeping the one input at the moment - but I wanted the code in there as I migrated things across (may keep the Sonos CONNECT, that was going via the C4 Controller)

Slowly figuring out how to migrate away from the C4 I inherited in the house when we bought it!

Thank you once again for taking the time to look at this.

**Comment by kmakar89** [comment]
everything else looks fine EXCEPT:         "initial_state: true" should be under the line "alias: alias: Kitchen Amp Input Override"

ie.

      - id: Kitchen Amp Input Override
        alias: Kitchen Amp Input Override
        initial_state: true
        trigger:
        - platform: state
          entity_id: input_select.kitchen_c4_input
        action:
        - service: input_select.select_option
          entity_id: input_select.kitchen_amp_input
          data_template:
    option: >-
        {% if is_state('input_select.kitchen_c4_input', 'House Chromecast') %}1
        {% elif is_state('input_select.kitchen_c4_input', 'House Sonos') %}2
        {% elif is_state('input_select.kitchen_c4_input', 'Control4 Input') %}3
        {% elif is_state('input_select.kitchen_c4_input', 'Blank2') %}4
        {% else %}1
        {%- endif %}


Try that out. If I were you (for simplicity sake) I'd implement it as I presented it (substituting your input names and rooms of course), this way you can select inputs (or leave it on House Chromecast) and in the future you can add inputs as desired.

This way each room has it's own input select (or can be left alone), and the power switch can turn on or off each zone (room) along with independent sound controls for each room. Just my .02.

**Comment by DeviousAl** [comment]
> everything else looks fine EXCEPT: "initial_state: true" should be under the line "alias: alias: Kitchen Amp Input Override"
> 
> ie.
> 
> ```
>   - id: Kitchen Amp Input Override
>     alias: Kitchen Amp Input Override
>     initial_state: true
>     trigger:
>     - platform: state
>       entity_id: input_select.kitchen_c4_input
>     action:
>     - service: input_select.select_option
>       entity_id: input_select.kitchen_amp_input
>       data_template:
> option: >-
>     {% if is_state('input_select.kitchen_c4_input', 'House Chromecast') %}1
>     {% elif is_state('input_select.kitchen_c4_input', 'House Sonos') %}2
>     {% elif is_state('input_select.kitchen_c4_input', 'Control4 Input') %}3
>     {% elif is_state('input_select.kitchen_c4_input', 'Blank2') %}4
>     {% else %}1
>     {%- endif %}
> ```
> 
> Try that out. If I were you (for simplicity sake) I'd implement it as I presented it (substituting your input names and rooms of course), this way you can select inputs (or leave it on House Chromecast) and in the future you can add inputs as desired.
> 
> This way each room has it's own input select (or can be left alone), and the power switch can turn on or off each zone (room) along with independent sound controls for each room. Just my .02.

Yeah I tried to keep as close to yours as I could, then strip the inputs back to the single 1 - House Chromecast. Then as you say, if/when I plug more things in, I simply give them a new name and add them to the list for each Room.

Initial State was towards the top - it changed when I looked at the automation in YAML through HA!

**Comment by kmakar89** [comment]
Try this out (this is what I do).

https://www.home-assistant.io/docs/configuration/splitting_configuration/

If you split the configuration and just have separate files for the C4 services, they don't get touched when you make changes in the UI and they stay static until you change them.

**Comment by DeviousAl** [comment]
> Try this out (this is what I do).
> 
> https://www.home-assistant.io/docs/configuration/splitting_configuration/
> 
> If you split the configuration and just have separate files for the C4 services, they don't get touched when you make changes in the UI and they stay static until you change them.

Thanks - just played around with it - moved automations in to a new directory and created a c4_automations.yaml and merged those in to config. Then moved the c4_services to an !include c4_services.yaml - so they are now both out of main config and automation files.

Thanks for the pointer!

**Comment by DeviousAl** [comment]
> Try this out (this is what I do).
> 
> https://www.home-assistant.io/docs/configuration/splitting_configuration/
> 
> If you split the configuration and just have separate files for the C4 services, they don't get touched when you make changes in the UI and they stay static until you change them.

Ok looks like I've broken something 🤣 - automations pulled through ok, but the c4_services and relevant entities aren't. Time to troubleshoot!

**Comment by kmakar89** [comment]
Services must always stay in custom_components/c4_services, the others can go in separate files.

**Comment by DeviousAl** [comment]
> Services must always stay in custom_components/c4_services, the others can go in separate files.

That might be where I went wrong, I think I had the c4_services piece in main config file!

**Comment by kmakar89** [comment]
Services are all the files that go into custom_components/c4_services, the rest is in config and automations. Splitting out automations is what I was referring to mostly.

**Comment by DeviousAl** [comment]
Ok I've really confused myself now!

Can I clarify:

In the services.yaml that is where I paste in:

    # Service
    c4_services:
    
    input_select:
      kitchen_c4_input:
        name: Audio Input
        options:
          - House Chromecast
      kitchen_amp_input:
        name: Zone Input
        options:
          - 1
    input_number:
      kitchen_amp_volume:
        name: Volume
        min: 0
        max: 1
        step: .01
        initial: .04
    input_boolean:
      switch_state_1:
        name: Kitchen Switch
    switch:
      - platform: template
        switches:
          kitchen_switch:
            friendly_name: Kitchen
            unique_id: kitchen_c4_switch_uid
            value_template: "{{ is_state('input_boolean.switch_state_1', 'on') }}"
            turn_on:
              - service: c4_services.handle_kitchen_amp_on_select
              - service: input_boolean.turn_on
                data:
                  entity_id: input_boolean.switch_state_1
            turn_off:
              - service: c4_services.handle_kitchen_amp_off_select
              - service: input_boolean.turn_off
                data:
                  entity_id: input_boolean.switch_state_1

Then, in configuration.yaml I have to simply insert:

            c4_services:


As part of the install / upgrade you state:

            Stop Home Assistant
            Remove/Rename/Delete c4_services.py
            Copy the c4_services folder into the custom_components folder
            Open __ init __.py (underscore underscore init underscore underscore.py) and change the IP Address of your AMP and Tuner in all instances.
            Start Home Assistant

I realised I've never seen the c4_services.py created anywhere, but I do see the __pycache__ created in the c4_services folder.

I must have misunderstood a step or something.

Just to state I had the c4_services and the switches / input select pieces of code all in the configuration.yaml previously.

**Comment by kmakar89** [comment]
The folder custom_components/c4_services is where the __init.py__, manifest.json, and services.yaml go.

The configuration settings go into the configuration.yaml file, and the automations go into the automations file, but you can make an additional file that get "read" with automations.yaml (if you choose to separate them which I did).

**Comment by DeviousAl** [comment]
> The folder custom_components/c4_services is where the **init.py**, manifest.json, and services.yaml go.
> 
> The configuration settings go into the configuration.yaml file, and the automations go into the automations file, but you can make an additional file that get "read" with automations.yaml (if you choose to separate them which I did).

Thank you for clarifying - I moved it back in to configuration.yaml - left the main services.yaml in custom_components/cs_services as blank, cleared the cache and rebooted HA - the entities came back again as expected.

The automations being moved out as the split files works, so thanks for that pointer.

Just tried the toggle a few times again on the various zones and did cause a reboot on the AMP - I think under "normal use" the sporadic odd turn on/off I should be fine - just seemed too many on/off calls in the toggle can make my amp crash!!

Appreciate you taking the time - let me buy you a virtual beer.

**Comment by kmakar89** [comment]
Your amp may be newer than mine, or not been upgraded in quite some time. That's possibly the issue.

No problem, good luck with moving away from C4. Took me about 2 weeks to change everything out (switches / sensors / door locks and such. I sold all the C4 stuff on ebay and I made out pretty good and expanded my system even further.

Good luck.
